#! /usr/bin/env python
#
# Support module generated by PAGE version 4.5
# In conjunction with Tcl version 8.6
#    Jul 25, 2015 03:17:22 PM

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk

    py3 = 0
except ImportError:
    import tkinter.ttk as ttk

    py3 = 1

api = None


def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global list_set_var
    list_set_var = StringVar()

    global edit_set_var
    edit_set_var = StringVar()

    global edit_hint_var
    edit_hint_var = StringVar()


def list_sel_update():
    edit_set_var.set(w.list_set.get(w.list_set.curselection()))

def update_list():
    sets = api.get_all_sets()
    list_set_var.set(' '.join(sets))
    cur = api.get_current_set()
    w.list_set.selection_set(sets.index(cur))
    list_sel_update()

def txt_read(txt):
    return txt.get("1.0", END)

def txt_clr(txt):
    txt.delete("1.0", END)

def commit(p1):
    v_set = edit_set_var.get()
    v_qst = txt_read(w.txt_question)
    v_hint = edit_hint_var.get()
    v_ans = txt_read(w.txt_answer)
    edit_set_var.set('')
    edit_hint_var.set('')
    txt_clr(w.txt_question)
    txt_clr(w.txt_answer)
    api.create_card(v_set, v_qst, v_hint, v_ans)
    update_list()

def init(top, gui, arg=None):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    global api
    api = arg
    update_list()


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None
